### ISSUE TITLE
Navbar.jsx: Fix Navbar.jsx 

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#1]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=12-364&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Using the above design, based on the auth state,
1) If the user is logged in, we need to have the following nav elements: Requests, My Requests, My Profile, About Us and Log Out.
2) If the user isn't logged in, we need to have the following nav elements: Home and About Us

**Comment by griseduardo** [comment]
Hello, I would like to work in this issue

**Comment by sikehish** [comment]
I've assigned it to you. Good luck!

**Comment by griseduardo** [comment]
Hello, I opened the pr here: https://github.com/gdsc-jssstu/campUS-Web/pull/6
