### ISSUE TITLE
Implement logout functionality

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#13]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=12-364&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Referring to the designs above,
1) Implement logout functionality.
2) Also, create link/button for it in the navbar as shown in the design below

![image](https://github.com/gdsc-jssstu/campUS-Web/assets/90673701/91b2c329-44da-41e7-87b9-62654e536f13)

**Comment by skj1709** [comment]
@sikehish Would you please assign this issue to me.

**Comment by sikehish** [comment]
Good luck! I've assigned it to you
