### ISSUE TITLE
AboutUs.jsx: Implement the component.

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#14]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=12-364&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Referring to the designs above,
1) Create an aesthetic and responsive About us Page, and stick to the hex codes using in the design.
2) AboutUs.jsx can be found in src/pages directory.
3) You can use Lorem Ipsum (dummy text) for now.

**Comment by skj1709** [comment]
@sikehish Would you please assign me this issue.

**Comment by sikehish** [comment]
Ive assigned it to you. Good luck!
