### ISSUE TITLE
Profile.jsx: Create user profile page

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#16]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=4-126&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Referring to the designs above,
1) Create an aesthetic and responsive Profile Page(pertaining to the currently logged in user), and stick to the hex codes using in the design.
2) The user has to be authenticated before creating a request
3) You have to link the Edit Profile button(as can be seen in the Profile page design below) to the Edit Profile page(which may or may not have been implemented by the time you would have come across this issue). Likewise, you need link View Requests link to the Requests Page.
4) You can find Profile.jsx in src/pages directory.

![image](https://github.com/gdsc-jssstu/campUS-Web/assets/90673701/fac6aef4-4a8b-4a21-b8af-afb443a336db)

**Comment by supunvindula** [comment]
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by sakshivbp1812** [comment]
@supunvindula Could you please assign it to me?..as i have already begun working on it..

**Comment by sikehish** [comment]
> Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.
> 
> Looking forward to your response. Thanks!

Hi @supunvindula. Ive assigned it to you. Good luck!

**Comment by sikehish** [comment]
> @supunvindula Could you please assign it to me?..as i have already begun working on it..

Hi @sakshipatil4403. Appreciate your eagerness to contribute, but assignment is based on first come first serve. If we do not get a  timely contribution, then we shall assign it to you. In the meantime, you can look into other issues listed, or create an issue if you feel that something needs to be addressed.

**Comment by supunvindula** [comment]
@sikehish i have started working on it

**Comment by supunvindula** [comment]
https://github.com/gdsc-jssstu/campUS-Web/pull/24

**Comment by supunvindula** [comment]
Here is the pull request for suggested edits. 
![image](https://github.com/gdsc-jssstu/campUS-Web/assets/59873941/b4f9aa4c-2465-4850-b247-40acd6feac99)
[Pull Request](https://github.com/gdsc-jssstu/campUS-Web/pull/24)

**Comment by sikehish** [comment]
Looks awesome!

**Comment by supunvindula** [comment]
Good to hear. Merge it if there is no problem
