### ISSUE TITLE
App.jsx: Enhance Routing

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#2]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=12-364&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)

Using the above design, based on the auth state,
1) Add relevant routes, and protect the routes wherever necessary. Few routes are already handled, you just need to extend on it.

**Comment by griseduardo** [comment]
Hello, I would like to work in this issue

**Comment by Vansh-Narang** [comment]
Hey , Can you assign this task to me ?

**Comment by sikehish** [comment]
> Hey , Can you assign this task to me ?

Hi Narang. Ive assigned it to @griseduardo . If I dont get any response from him, then it'll be up for grabs again.

**Comment by sikehish** [comment]
> Hello, I would like to work in this issue

Good luck! Ive assigned it to you

**Comment by Vansh-Narang** [comment]
okay sure !

**Comment by griseduardo** [comment]
Hello, I opened the pr here: https://github.com/gdsc-jssstu/campUS-Web/pull/9
