### ISSUE TITLE
AboutUs.jsx: Come up with some good content to replace the placeholder/dummy text in About Us page

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#22]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=12-364&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Unlike other issues, there is no right or wrong solution to this issue. We expect you to be creative and come up with a description under About Us, that is apt, succinct, yet creative and engaging. Issue would be assigned based on the approach that you suggest in the comments. 

Component path: /src/pages/AboutUs.jsx

**Comment by kushvendar** [comment]
hey @sikehish  can i work on this ?

**Comment by sikehish** [comment]
@kushvendar Sure! You can start working on this, good luck!

**Comment by sikehish** [comment]
Please keep me updated about the content that you're including.

**Comment by kushvendar** [comment]
hey @sikehish  i have updted the content created a pr with attached screenshot kindly check

**Comment by sikehish** [comment]
> hey @sikehish i have updted the content created a pr with attached screenshot kindly check

@kushvendar  Thanks for the contribution, appreciate the efforts! Looking forward to more contributions from your end. Please star the repo if you like what we're building; it helps!

**Comment by kushvendar** [comment]
hey @sikehish thanks a lot
