### ISSUE TITLE
Home.jsx: Come up with some good content to replace the placeholder/dummy text under Features section in Home page. 

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#23]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=12-364&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Unlike other issues, there is no right or wrong solution to this issue. We expect you to be creative and come up with a description under Features, that is apt, succinct, yet creative and engaging. Issue would be assigned based on the approach that you suggest in the comments. 

Also, coming up with a figma design would be a plus point. You can come up with some cool layouts to explain the features(list of features can be extracted from the issues/PRs made, README.md and the above figma design link).

Component path: /src/pages/Home.jsx

**Comment by supunvindula** [comment]
Hi there! I'm interested in working on this issue. Could you please assign it to me? I believe I can make a valuable contribution to this task.

Looking forward to your response. Thanks!

**Comment by sikehish** [comment]
Could you explain your approach. Would you create a grid(which I think would look cool) or anything else?

**Comment by supunvindula** [comment]
We can create a grid with one feature per one grid. Or else I would like to do a changing card with features showing one at a time and automatically changing

**Comment by supunvindula** [comment]
Also do you have any images to use for the feature section? And any specific feature list that i might want to add?

**Comment by sikehish** [comment]
I'd love to see the changing card with features showing one at a time approach. You can proceed with that. You can use react-icons or some some animated icons instead of images.

**Comment by supunvindula** [comment]
Hi. this issue is resolved by this  [PR](https://github.com/gdsc-jssstu/campUS-Web/pull/26)

**Comment by supunvindula** [comment]
![image](https://github.com/gdsc-jssstu/campUS-Web/assets/59873941/d07f9a79-0a2f-4467-ab23-346a8b892598)
Now it changes

**Comment by sanjay14073** [comment]
Hey @supunvindula, would just like to suggest two improvements one is the image the image isnt fully wrapped.it should be fitting within the div so some minor css changes are required and also try to improve on the card's background color

**Comment by supunvindula** [comment]
Yeah, I am trying to do the color change and still trying to figure it out. I can fully include the image but then it will be smaller if i take it to the size of the card. If I make the image larger to fit into the left side then the card will be still smaller.

**Comment by sanjay14073** [comment]
@supunvindula Just try to contain the image using simple css

**Comment by sanjay14073** [comment]
@supunvindula  any update?

**Comment by supunvindula** [comment]
https://github.com/gdsc-jssstu/campUS-Web/pull/26
Hi I have completed the task. Check the PR again

**Comment by sanjay14073** [comment]
Is the image part done too @supunvindula

**Comment by supunvindula** [comment]
Yes

**Comment by sanjay14073** [comment]
@supunvindula  Done will review it once and let you know the update shortly

**Comment by sanjay14073** [comment]
@supunvindula  The PR is good to go. Thank You.
