### ISSUE TITLE
EditProfile.jsx: Implement Edit Profile page for the authenticated user.

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#25]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=4-126&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Referring to the designs above,
1) Create an aesthetic and responsive EditProfile Page(pertaining to the currently logged in user), and stick to the hex codes using in the design.
2) The user has to be authenticated before creating a request.
3) You have to link the Edit Profile button(as can be seen in the Profile page design below) to the Edit Profile page.
4) You can find EditProfile.jsx in src/pages directory.
5) Add EditProfile route as "edit-profile"

![image](https://github.com/gdsc-jssstu/campUS-Web/assets/90673701/fac6aef4-4a8b-4a21-b8af-afb443a336db)
![image](https://github.com/gdsc-jssstu/campUS-Web/assets/90673701/9b76eaa6-5318-4420-8218-c8769633e660)

**Comment by Nupoor10** [comment]
Hello, can I work on this? @sikehish

**Comment by sikehish** [comment]
Hey @Nupoor10, sure. Go ahead. Good luck!

**Comment by hamzailyas237** [comment]
I want to work on this. Assign it to me.

**Comment by sikehish** [comment]
Hi @hamzailyas237 , This issue is already assigned. If the assignee fails to accomplish the desired goals, then we shall assign it to you.

**Comment by Nupoor10** [comment]
Hello @sikehish, I have implemented the UI of the page, along with fetching user details. Do I have to implement the edit functionality in firebase as well? Here is the UI for your reference : 
![image](https://github.com/gdsc-jssstu/campUS-Web/assets/92589912/5ce0233f-6aa8-437e-8d50-593e261cc2cf)
![image](https://github.com/gdsc-jssstu/campUS-Web/assets/92589912/e11aa9c3-8cb1-4689-b6e7-ab5d8bdb3b14)

**Comment by sikehish** [comment]
Hey, great work! Can you implement it using firebase? Let me know if that can be done. If not, then no worries. Also, is the name and  phone number editable(i.e is the content modifiable?)
