### ISSUE TITLE
Home.jsx: Fix the Get Started button(only on Firefox browsers)

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#27]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=4-126&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

As you can see in the image below, the Get Started text isn't really fitting into the button. This issue is ONLY on Firefox browsers, and not on chrome. You need to get the placement of the text right.

Home.jsx can be found in src/pages.

![image](https://github.com/gdsc-jssstu/campUS-Web/assets/90673701/ed41615c-6e94-4601-b4b4-bcbbbc8ea337)

**Comment by kushvendar** [comment]
hey @sikehish  can i work on this ?

**Comment by sikehish** [comment]
Sure! Once you're done, send me screenshots of the get started button on both chrome and firefox.

**Comment by kushvendar** [comment]
hey @sikehish  i am getting file error while setting up this project 
 /*  [vite] Internal server error: Cannot redefine property: File */
File Location :-   campUS-Web/src/main.jsx
please check it out

**Comment by sikehish** [comment]
Hi @kushvendar, It's working fine on my end. Can you please elaborate on the issue that you've faced, and what led you to that issue?

**Comment by kushvendar** [comment]
sure @sikehish  after setting up the project 
1.installing dependencies  
2.Replace Firebase Configuration
3. after executing npm run dev command i got this error
<img width="1440" alt="Screenshot 2023-10-25 at 9 35 45 AM" src="https://github.com/gdsc-jssstu/campUS-Web/assets/102733596/51aa350e-a3ce-4720-a361-53fc61e14f57">

**Comment by sikehish** [comment]
There are two things you can do. Either clone the repository once again(and sync all the changes using the sync button on the forked repo page) and do git pull, OR search up for the error online, I haven't come across this error till now, so I'm assuming they there's some issue with npm/Node version on your end.

**Comment by kushvendar** [comment]
ok i will try this

**Comment by kushvendar** [comment]
hey @sikehish i have resolved the issue and raised a PR kindly check
