### ISSUE TITLE
Home.jsx: Implement the home/landing page design as per the figma files

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#3]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=12-364&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Using the above design
1) Implement the design for the home page. For the features section, feel free to reach out to @sikehish for the text content.
2) Stick to the hex codes used in the design and ensure that it is responsive. If Navbar.jsx isn't implemented yet, then we would recommend you to take up that issue first. [Navbar issue](https://github.com/gdsc-jssstu/campUS-Web/issues/1)

**Comment by skj1709** [comment]
Hi @sikehish @ghpranav @chandansgowda @ShivamMenda please assign me this issue under hacktoberfest2023.

**Comment by sikehish** [comment]
I've assigned it to you. Good luck Sumit!

**Comment by Jineshbansal** [comment]
@sikehish as a part of hacktober fest 2023 , I wish to contribute to your website .Please assign this issue to me

**Comment by sikehish** [comment]
> @sikehish as a part of hacktober fest 2023 , I wish to contribute to your website .Please assign this issue to me

Hi Jinesh. Appreciate your enthusiasm, but for now it assigned to @sumit-kumar-jha1709 .

**Comment by skj1709** [comment]
@sikehish can you provide the text content, under the Feature heading

**Comment by sikehish** [comment]
@sumit-kumar-jha1709 Hi Sumit, you can stick to some dummy content for now.

**Comment by skj1709** [comment]
Okay @sikehish
