### ISSUE TITLE
Login.jsx: Implement Login functionality using Firebase Authentication

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#4]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=12-364&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Referring to the designs above,
1) Create an aesthetic and responsive Login Page, and stick to the hex codes using in the design.
2) Refer to context/AuthContext.jsx, where functionality for login is provided. Integrate it and using onSubmit handler, you are required to authenticate the user.

**Comment by skj1709** [comment]
Hi @sikehish please assign me this issue under Hacktoberfest2023

**Comment by sikehish** [comment]
I've assigned it to you. Good luck!

**Comment by sikehish** [comment]
@sumit-kumar-jha1709 Any update?
