### ISSUE TITLE
Signup.jsx: Implement Signup functionality using Firebase Authentication

### ISSUE THREAD

**Issue by sikehish** [gdsc-jssstu/campUS-Web#5]
[Design link](https://www.figma.com/proto/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=12-364&t=9JuB3TEFpHrqwBXt-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A364)
[Hex Codes](https://www.figma.com/file/MfbtIqwt0fjPtmWOuQ7yCQ/CampUs?type=design&node-id=0-1&mode=design&t=cuY9XjlQ8EewwaTM-0)

Referring to the designs above,
1) Create an aesthetic and responsive Signup Page, and stick to the hex codes using in the design.
2) Refer to context/AuthContext.jsx, where functionality for signup is provided. You need to implement the signup method in the onSubmit handler.
3) On signup, I want a user, having a document ID set to that of the corresponding User UID(Firebase Auth), to be created in the users collection, where you store additional data related to the user(essentially all the details related to the user except for the password).

**Comment by skj1709** [comment]
Hi @sikehish please assign me this issue under Hacktoberfest2023

**Comment by sikehish** [comment]
I've assigned it to you. Good luck!

**Comment by sikehish** [comment]
@sumit-kumar-jha1709 Any update?

**Comment by skj1709** [comment]
hi @sikehish working on final styling.

**Comment by sikehish** [comment]
@sumit-kumar-jha1709 Alright.
